name: senhasegura CLI CI/CD DEMO

on:
  push:
    branches:
      - master

jobs:
  DJARRIN:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Unit Tests
        run: mvn clean package
      
      - name: Deploy and Get Secret DSM Senhasegura
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          SYSTEM: ${{ secrets.SYSTEM }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
            chmod 777 dsm-linux-amd64
            ./dsm-linux-amd64 runb --application $APPLICATION --system $SYSTEM --environment $ENVIRONMENT --config .config.yaml --tool github
          
      - name: Run Jar
        run: java -jar target/demo-dsm-0.0.1-SNAPSHOT.jar